### ISSUE TITLE
console.hud_alert bug

### ISSUE THREAD

**Issue by disorientedperson** [omz/PythonistaAppTemplate#1]
With hud_alert using the template, I see a loading alert instead of a check mark or X. This works fine within Pythonista. Screenshot:  
![image](https://cloud.githubusercontent.com/assets/14137956/13099064/3cdd9766-d4f4-11e5-883f-5485b6b83fee.png)

**Comment by omz** [comment]
Thanks, should be fixed with 6539e014bb478e9906e08aacfbbf0d2676df4157.
