### ISSUE TITLE
template simulator inconsistencies

### ISSUE THREAD

**Issue by Tkizzy** [omz/PythonistaAppTemplate#3]
So it appears that the template seems to run on the 64 bit simulators this time, but not the non-64-bit ones.
**works:**
iPad Air
iPad Air 2
iPhone 5S
iPhone 6
iPhone 6+
iPhone 6S
iPhone 6S Plus

*(OCCASIONALLY the above simulators, although the build succeeds will fail with this popup error dialogue:
"The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)"

(In one incarnation of the template where I tried to migrate all my scripts I got the above message non-stop...I'm not sure why. But I made a fresh "checkout" without anything added and it seemed to happen pretty rarely.)

**Doesn't Work and throws the same errors below**
iPad Retina:
iPad2:
iPhone 4s:
iPhone 5:

`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_OMTextAttachment", referenced from:
      objc-class-ref in libpythonista_appui.a(PAStandaloneOutputView.o)
  "_OBJC_CLASS_$_OMTextColorTheme", referenced from:
      objc-class-ref in PAAppViewController.o
  "_OBJC_CLASS_$_OMTextView", referenced from:
      objc-class-ref in libpythonista_appui.a(PAStandaloneOutputView.o)
  "_createAttachmentRunDelegate", referenced from:
      -[PAStandaloneOutputView outputImage:atPath:] in libpythonista_appui.a(PAStandaloneOutputView.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by omz** [comment]
The "operation could not be completed" errors are probably Xcode bugs. It might help to restart the simulator.

The issue with building for 32-bit simulators should be fixed with d4051dc95701608d5e6b67d36160df08f245988c.
