### ISSUE TITLE
deployment target before 9.2 warning

### ISSUE THREAD

**Issue by Tkizzy** [omz/PythonistaAppTemplate#4]
If you try to deploy to 8.1, you get the following warning:

`Object file (/Users/anty/Documents/devAndGraphic/xCode7era Dev/FiveStarsV2/PythonistaAppTemplate/libpythonista_appui.a(PAStandaloneOutputView.o)) was built for newer iOS version (9.2) than being linked (8.1)
`

**Comment by omz** [comment]
Should also be fixed with d4051dc95701608d5e6b67d36160df08f245988c.
